import { useEffect, useMemo, useState } from "react";
import API from "../services/api";
import "./DecisionHistory.css";

function DecisionHistory() {
  const [history, setHistory] = useState([]);
  const [search, setSearch] = useState("");
  const [riskFilter, setRiskFilter] = useState("All");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [deletingId, setDeletingId] = useState(null);

  useEffect(() => {
    loadHistory();
  }, []);

  const loadHistory = async () => {
    try {
      setLoading(true);
      setError("");

      const response = await API.get("/history");

      setHistory(response.data);
    } catch (err) {
      console.error(err);
      setError("Could not load decision history.");
    } finally {
      setLoading(false);
    }
  };

  const deleteDecision = async (id) => {
    const confirmed = window.confirm(
      "Are you sure you want to delete this decision?"
    );

    if (!confirmed) {
      return;
    }

    try {
      setDeletingId(id);
      setError("");

      await API.delete(`/history/${id}`);

      setHistory((currentHistory) =>
        currentHistory.filter((item) => item.id !== id)
      );
    } catch (err) {
      console.error(err);

      setError(
        err.response?.data?.detail ||
          "Could not delete the selected decision."
      );
    } finally {
      setDeletingId(null);
    }
  };

  const filteredHistory = useMemo(() => {
    return history.filter((item) => {
      const matchesSearch =
        item.supplier
          ?.toLowerCase()
          .includes(search.toLowerCase()) ||
        item.recommendation
          ?.toLowerCase()
          .includes(search.toLowerCase());

      const matchesRisk =
        riskFilter === "All" ||
        item.risk?.toLowerCase() === riskFilter.toLowerCase();

      return matchesSearch && matchesRisk;
    });
  }, [history, search, riskFilter]);

  const totalDecisions = history.length;

  const highRisk = history.filter(
    (item) => item.risk === "High"
  ).length;

  const mediumRisk = history.filter(
    (item) => item.risk === "Medium"
  ).length;

  const lowRisk = history.filter(
    (item) => item.risk === "Low"
  ).length;

  const getRiskClass = (risk) => {
    if (risk === "High") return "history-risk-high";
    if (risk === "Medium") return "history-risk-medium";
    return "history-risk-low";
  };

  return (
    <div className="history-page">

      {/* HEADER */}

      <div className="history-header">

        <div>

          <span className="history-eyebrow">
            DECISION INTELLIGENCE
          </span>

          <h1>
            Decision History
          </h1>

          <p>
            Review previous supplier assessments, risk levels,
            and recommendations generated by SupplyPilot-AI.
          </p>

        </div>

        <button
          className="history-refresh-button"
          onClick={loadHistory}
          disabled={loading}
        >
          {loading ? "Refreshing..." : "Refresh"}
        </button>

      </div>


      {/* ERROR */}

      {error && (
        <div className="history-error">
          {error}
        </div>
      )}


      {/* SUMMARY */}

      <div className="history-summary-grid">

        <div className="history-summary-card">

          <span>
            Total Decisions
          </span>

          <strong>
            {totalDecisions}
          </strong>

          <small>
            All supplier assessments
          </small>

        </div>


        <div className="history-summary-card history-summary-high">

          <span>
            High Risk
          </span>

          <strong>
            {highRisk}
          </strong>

          <small>
            Require immediate attention
          </small>

        </div>


        <div className="history-summary-card history-summary-medium">

          <span>
            Medium Risk
          </span>

          <strong>
            {mediumRisk}
          </strong>

          <small>
            Require monitoring
          </small>

        </div>


        <div className="history-summary-card history-summary-low">

          <span>
            Low Risk
          </span>

          <strong>
            {lowRisk}
          </strong>

          <small>
            Normal monitoring
          </small>

        </div>

      </div>


      {/* TABLE SECTION */}

      <div className="history-section">

        <div className="history-section-header">

          <div>

            <span className="history-section-label">
              SUPPLIER DECISIONS
            </span>

            <h2>
              Assessment Records
            </h2>

            <p>
              Search and filter your previous assessments.
            </p>

          </div>

        </div>


        {/* FILTERS */}

        <div className="history-controls">

          <div className="history-search">

            <input
              type="text"
              placeholder="Search supplier or recommendation..."
              value={search}
              onChange={(event) =>
                setSearch(event.target.value)
              }
            />

          </div>


          <div className="history-filter">

            <select
              value={riskFilter}
              onChange={(event) =>
                setRiskFilter(event.target.value)
              }
            >

              <option value="All">
                All Risks
              </option>

              <option value="High">
                High Risk
              </option>

              <option value="Medium">
                Medium Risk
              </option>

              <option value="Low">
                Low Risk
              </option>

            </select>

          </div>

        </div>


        {/* LOADING */}

        {loading && (
          <div className="history-state">
            <div className="history-spinner"></div>
            <p>
              Loading decision history...
            </p>
          </div>
        )}


        {/* EMPTY */}

        {!loading && filteredHistory.length === 0 && (
          <div className="history-state">

            <div className="history-empty-icon">
              H
            </div>

            <h3>
              No decisions found
            </h3>

            <p>
              {history.length === 0
                ? "Run a supplier prediction or recommendation to create your first decision."
                : "Try changing your search or risk filter."}
            </p>

          </div>
        )}


        {/* TABLE */}

        {!loading && filteredHistory.length > 0 && (

          <div className="history-table-wrapper">

            <table className="history-table">

              <thead>

                <tr>

                  <th>
                    ID
                  </th>

                  <th>
                    Supplier
                  </th>

                  <th>
                    Quantity
                  </th>

                  <th>
                    Risk
                  </th>

                  <th>
                    Recommendation
                  </th>

                  <th>
                    Timestamp
                  </th>

                  <th>
                    Action
                  </th>

                </tr>

              </thead>


              <tbody>

                {filteredHistory.map((item) => (

                  <tr key={item.id}>

                    <td className="history-id">
                      #{item.id}
                    </td>

                    <td className="history-supplier">
                      {item.supplier}
                    </td>

                    <td>
                      {item.quantity}
                    </td>

                    <td>

                      <span
                        className={`history-risk ${getRiskClass(
                          item.risk
                        )}`}
                      >
                        {item.risk}
                      </span>

                    </td>

                    <td className="history-recommendation">
                      {item.recommendation}
                    </td>

                    <td className="history-timestamp">
                      {item.timestamp}
                    </td>

                    <td>

                      <button
                        className="history-delete-button"
                        onClick={() =>
                          deleteDecision(item.id)
                        }
                        disabled={deletingId === item.id}
                      >
                        {deletingId === item.id
                          ? "Deleting..."
                          : "Delete"}
                      </button>

                    </td>

                  </tr>

                ))}

              </tbody>

            </table>

          </div>

        )}

      </div>

    </div>
  );
}

export default DecisionHistory;